[tool.poetry]
name = "poetry-web"
version = "0.1.0"
description = ""
authors = ["Tomi Nieminen <tomi.s.nieminen@helsinki.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
